#!/usr/bin/env bash
# Configures Nginx with a custom X-Served-By HTTP response header

apt-get update -y
apt-get install -y nginx

cat > /etc/nginx/sites-available/default <<NGINX
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
NGINX

nginx -t && service nginx restart
