#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02 using round-robin

apt-get update -y
apt-get install -y haproxy

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg <<HAPROXY
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7047-web-01 34.201.51.178:80 check
    server 7047-web-02 54.158.123.226:80 check
HAPROXY

service haproxy restart
